// <auto-generated />
using CasePriority.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasePriority.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CasePriorityDbContext))]
    partial class CasePriorityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasePriority.Core.Domain.SupportCase", b =>
                {
                    b.Property<string>("CaseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("IsExecutiveEscalation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("Version");

                    b.HasKey("CaseNumber");

                    b.ToTable("SupportCases", null, t =>
                        {
                            t.HasCheckConstraint("CK_SupportCases_Severity", "[Severity] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_SupportCases_Version", "[Version] >= 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
